# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Mod Information
mod.version=0.15.2
mod.name=insecticide-lib
mod.maven_group = nl.enjarai
mod.target=[VERSIONED]
mod.target_min=[VERSIONED]
mod.target_max=[VERSIONED]
mod.target_nice=[VERSIONED]
mod.jarname_target=[VERSIONED]

mod.modrinth=QM3qgW2x
mod.github=Tigercrl/insecticide-lib

# Dependencies
# https://fabricmc.net/develop
deps.yarn=[VERSIONED]
deps.fabric_loader=0.19.3
deps.fabric_api=[VERSIONED]
deps.snakeyaml=2.2
